# Import Libaries

In [6]:
from sklearn.datasets import load_iris

## Load Data

In [7]:
iris = load_iris()
X = iris.data
y = iris.target

In [8]:
# verify the shapes of X & y
print(X.shape)
print(y.shape)

(150, 4)
(150,)


## Import Classifiers

In [9]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

## Fit the model with data

In [10]:
print knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


In [11]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

## Pridict the response for a new obervation

In [12]:
knn.predict([4,2,3,1])

/usr/local/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])

In [13]:
# You can also make multiple predictions using 2d array
X_new = [(3,5,4,2), [4,3,5,2]]
knn.predict(X_new)

array([2, 2])

### Using a different model for K

In [14]:
# You can change the value of n_neighbors=x
knn2 = KNeighborsClassifier(n_neighbors=5)

In [15]:
knn2.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [16]:
knn2.predict([2,3,4,5])

/usr/local/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])